backend:
  name: github
  repo: msoes/KanzleiConnectSite
  branch: main
  base_url: https://9z1y21guoe.execute-api.eu-central-1.amazonaws.com

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "gallery"
    label: "Galerie"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "gallery"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Photos"
        name: "photos"
        widget: "list"
        field: {label: "Photo", name: "photo", widget: "image"}
